---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: Testing
        location: westeurope
        tags: 
          test: 1
          hello: 2

